"""
SynthesisDaemon — local-LLM reflector. The third reflection daemon.

Reads recent chronicle entries and asks a local LLM (Qwen3.6:27B via Ollama
by default) to gesture at patterns the writing instances and the human in
the loop might have missed: cross-domain convergences, structural echoes,
untouched questions, tensions between distant entries.

Architectural break with the v1.3.2 daemon pattern, deliberate:
  * UncertaintyResurfacer + MetabolizeDaemon are NOTIFICATION PRIMITIVES.
    Templated digests, zero LLM, zero hallucination surface, comms posts
    with ack-required circuit breakers. They surface what's already in
    the chronicle in a different shape.
  * SynthesisDaemon is INTERPRETIVE. It generates new reading. It is
    fallible by design. The reader is the calibration mechanism — every
    arriving Claude sees reflections framed as "machine-generated by
    <model>; some will be insight, some nonsense; ack/engage/discard."
  * Therefore: no comms post, no halt-on-unacked-digest, no
    grounded_extract invariant. The reflector earns its compute cost
    through ack-rate over time, not through gate-before-post.

Output sink: ~/.sovereign/reflections/<YYYY-MM-DD>.jsonl
  Each reflection is a JSON line with model + version + entries_referenced +
  connection_type + confidence + observation, plus daemon-side metadata
  (timestamp, prompt_version, run_id) for the eventual ack-rate analytics.

The chronicle proper (~/.sovereign/chronicle/insights/) stays untouched —
machine-generated reflections live in their own tree and are CITED at boot,
not merged into the human/Claude-authored layers.

Designed by mac-studio + Anthony, 2026-04-26 fireside. Run cadence is a
launchd plist decision, not coded here. Manually-invokable via __main__.
"""

from __future__ import annotations

import contextlib
import json
import os
import re
import time
import urllib.error
import urllib.request
import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

# ── Tunables ────────────────────────────────────────────────────────────────

DEFAULT_MODEL = "ministral-3:14b"  # fireside 2026-04-26: tested at 25s with
# Qwen-quality cross-entry synthesis on the test corpus. Sweet spot between
# llama3.1:8b (too small — surface restatements, occasional misreads) and
# qwen3.6:27b (~120s — too slow for interactive use). Keep Qwen as opt-in
# for the deep-nightly variant when latency doesn't matter.
DEFAULT_PROMPT_VERSION = "v1-2026-04-26"
DEFAULT_RECENT_HOURS = 36  # window of chronicle entries to read
DEFAULT_MAX_ENTRIES = 8  # cap on entries fed to the model
DEFAULT_TIMEOUT_SECONDS = 180  # 14B finishes in ~25-60s; 180s gives headroom

SOVEREIGN_ROOT = Path(os.path.expanduser("~/.sovereign"))
CHRONICLE_INSIGHTS = SOVEREIGN_ROOT / "chronicle" / "insights"
REFLECTIONS_DIR = SOVEREIGN_ROOT / "reflections"

OLLAMA_API_URL = os.getenv("OLLAMA_API_URL", "http://127.0.0.1:11434/api/generate")

# Shape requested in the prompt — each observation is a dict with these keys.
ALLOWED_CONNECTION_TYPES = frozenset(
    {
        "convergence",
        "contradiction",
        "structural_echo",
        "untouched_question",
        "drift_pattern",
        "other",
    }
)
ALLOWED_CONFIDENCE = frozenset({"low", "medium"})


# ── Data shape ──────────────────────────────────────────────────────────────


@dataclass
class Reflection:
    """One observation from the reflector."""

    observation: str
    entries_referenced: list[str]
    connection_type: str
    confidence: str

    def to_dict(self) -> dict[str, Any]:
        return {
            "observation": self.observation,
            "entries_referenced": self.entries_referenced,
            "connection_type": self.connection_type,
            "confidence": self.confidence,
        }


@dataclass
class RunResult:
    """Outcome of a single synthesis run."""

    outcome: str  # "wrote" | "no_entries" | "model_failed" | "parse_failed" | "skipped"
    details: str = ""
    run_id: str = ""
    model: str = ""
    reflections_written: int = 0
    reflections_path: str | None = None
    elapsed_seconds: float = 0.0
    raw_model_output: str = ""  # for debugging only; not persisted with reflections


# ── Chronicle reading ───────────────────────────────────────────────────────


def _iso_to_dt(s: str) -> datetime | None:
    try:
        return datetime.fromisoformat(s.replace("Z", "+00:00"))
    except (ValueError, TypeError):
        return None


def read_recent_chronicle(
    chronicle_root: Path = CHRONICLE_INSIGHTS,
    recent_hours: int = DEFAULT_RECENT_HOURS,
    max_entries: int = DEFAULT_MAX_ENTRIES,
) -> list[dict]:
    """
    Read the most recent insight entries within the time window.

    Returns a list of dicts, newest first, each with keys:
        timestamp (ISO), domain (str), layer (str), content (str),
        tag (short id derived from filename), session_id (str)

    Falls through with empty list if chronicle root doesn't exist —
    daemon callers should treat that as a no-op run.
    """
    if not chronicle_root.exists():
        return []

    cutoff = datetime.now(timezone.utc).timestamp() - (recent_hours * 3600)
    entries: list[dict] = []

    for domain_dir in chronicle_root.iterdir():
        if not domain_dir.is_dir():
            continue
        for jsonl_path in domain_dir.glob("*.jsonl"):
            try:
                lines = jsonl_path.read_text().splitlines()
            except OSError:
                continue
            for line in lines:
                line = line.strip()
                if not line:
                    continue
                try:
                    rec = json.loads(line)
                except json.JSONDecodeError:
                    continue
                ts = _iso_to_dt(rec.get("timestamp", ""))
                if ts is None:
                    continue
                if ts.timestamp() < cutoff:
                    continue
                entries.append(
                    {
                        "timestamp": rec.get("timestamp", ""),
                        "domain": rec.get("domain", "?"),
                        "layer": rec.get("layer", "?"),
                        "content": rec.get("content", ""),
                        "tag": domain_dir.name[:60],
                        "session_id": rec.get("session_id", ""),
                        "ts_epoch": ts.timestamp(),
                    }
                )

    entries.sort(key=lambda e: e["ts_epoch"], reverse=True)
    return entries[:max_entries]


# ── Prompt assembly ─────────────────────────────────────────────────────────


REFLECTOR_PREAMBLE = """\
You are a quiet observer reading a chronicle written by AI instances and a
human researcher (Anthony) over recent days. The chronicle is a structured
field — entries have domains, layers (ground_truth / hypothesis / open_thread),
timestamps, and sometimes addressed-letter shapes between sibling instances.

Your job is NOT to be authoritative. Your job is to gesture at the single
strongest pattern you notice that the humans-in-the-loop and the writing
instances might have missed — a point of convergence, an unresolved tension,
a structural echo across distant entries, or an untouched question. The
observation will be insight or nonsense — the reader knows this and will
calibrate.

Output exactly 1 observation as JSON, shaped like:
{
  "observation": "<one paragraph — make it count, you only get one>",
  "entries_referenced": ["<short entry tag>", ...],
  "connection_type": "convergence" | "contradiction" | "structural_echo" | "untouched_question" | "drift_pattern" | "other",
  "confidence": "low" | "medium"
}
Wrap it in {"reflections": [<the single object>]}. No prose outside the JSON.
"""


def build_prompt(entries: list[dict], focus: str | None = None) -> str:
    """
    Assemble the prompt with chronicle entries serialized as numbered blocks.

    Args:
        entries: chronicle records from read_recent_chronicle
        focus: optional steering hint (e.g. "register-drift" or "the
               relationship between simulator revival and truncation").
               When set, appended as a steering line so the reflector
               biases its observations toward that topic — but is still
               free to gesture at unrelated patterns it notices.
    """
    lines = [REFLECTOR_PREAMBLE, "", "═══════════════ CHRONICLE EXCERPT ═══════════════", ""]
    for i, e in enumerate(entries, 1):
        lines.append(
            f"[ENTRY {i}] {e['timestamp'][:19]} — domain={e['domain'][:80]}"
        )
        lines.append(f"LAYER: {e['layer']}")
        # Trim very long bodies but keep enough for the model to reason.
        content = e["content"]
        if len(content) > 1800:
            content = content[:1800] + " […truncated for prompt budget]"
        lines.append(content)
        lines.append("")
    lines.append("═══════════════ END CHRONICLE EXCERPT ═══════════════")
    lines.append("")
    if focus:
        lines.append(
            f"FOCUS: bias your observations toward the following topic but "
            f"stay free to surface unrelated patterns you notice — `{focus[:200]}`"
        )
        lines.append("")
    lines.append(
        "Now produce 1 observation as the JSON described above. "
        "Pick the strongest signal you see — gesture, don't declare. "
        "If you're wrong, that is allowed; the reader will calibrate."
    )
    return "\n".join(lines)


# ── Model call ──────────────────────────────────────────────────────────────


def call_ollama(
    prompt: str, model: str = DEFAULT_MODEL, timeout: int = DEFAULT_TIMEOUT_SECONDS
) -> tuple[bool, str]:
    """
    Call Ollama's HTTP /api/generate endpoint with stream=False so we get
    one clean JSON response. Returns (ok, output_text).

    HTTP API on purpose, not `ollama run`. The CLI does TTY-style streaming
    that leaks ANSI cursor-movement codes (\\x1b[6D, \\x1b[K) into stdout
    even when piped — those create character-rewrite duplication that
    corrupts the model's JSON output. Tested on ministral-3:14b at the
    2026-04-26 fireside; HTTP path is clean, CLI path is not.
    """
    payload = {
        "model": model,
        "prompt": prompt,
        "stream": False,
        # format=json forces the model to produce strictly valid JSON —
        # without it, ministral-3:14b occasionally emits unescaped inner
        # quotes ('recent "honks"') that break parsing. Caught at the
        # 2026-04-26 fireside when wiring synthesize_now with a focus
        # parameter triggered the failure mode.
        "format": "json",
        # Lower temperature for more disciplined adherence to schema.
        # num_predict raised from Ollama's default ceiling (~512-1024 tokens
        # depending on build) because `format=json` constrains shape, not
        # length — when ministral hit the default it produced truncated JSON
        # that broke the parser, losing 2 already-complete reflections to a
        # 3rd that never finished. 4096 leaves room for ~6 reflections worth
        # of full-prose observations. Caught at the 2026-04-26 04:17 firing.
        "options": {"temperature": 0.4, "num_predict": 4096},
    }
    body = json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(
        OLLAMA_API_URL,
        data=body,
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            raw_resp = resp.read().decode("utf-8")
    except urllib.error.URLError as exc:
        return False, f"ollama http error: {exc}"
    except TimeoutError:
        return False, f"ollama timed out after {timeout}s"

    try:
        data = json.loads(raw_resp)
    except json.JSONDecodeError as exc:
        return False, f"ollama returned non-JSON: {exc}"

    output = data.get("response", "")
    if not output:
        return False, f"ollama empty response: {raw_resp[:300]}"
    return True, output


# ── Output parsing ──────────────────────────────────────────────────────────

# Some Ollama models emit a thinking trace before the final JSON. Strip
# everything before the closing "...done thinking." marker if present.
_THINKING_TRAILER = re.compile(r"\.\.\.done thinking\.\s*", re.IGNORECASE)
_ANSI_ESCAPE = re.compile(r"\x1b\[[0-9;?]*[a-zA-Z]")


def extract_json_block(raw: str) -> str | None:
    """
    Find the JSON object in the raw model output. Handles:
      * ANSI escape codes from terminal streaming
      * thinking traces ending with "...done thinking."
      * markdown code fences ```json ... ```
      * stray prose around the JSON
    Returns the JSON string or None if no parseable block found.
    """
    cleaned = _ANSI_ESCAPE.sub("", raw)
    m = _THINKING_TRAILER.search(cleaned)
    if m:
        cleaned = cleaned[m.end() :]
    # Strip code fences if present.
    cleaned = re.sub(r"^```(?:json)?\s*", "", cleaned.strip(), flags=re.IGNORECASE)
    cleaned = re.sub(r"\s*```\s*$", "", cleaned)
    # Find first { and last } — naive but works for single top-level objects.
    start = cleaned.find("{")
    end = cleaned.rfind("}")
    if start == -1 or end == -1 or end <= start:
        return None
    return cleaned[start : end + 1]


def _recover_complete_reflections(block: str) -> list[dict]:
    """
    Walk the truncated JSON block character by character with a brace-depth
    counter, capturing each complete `{...}` object inside the top-level
    "reflections":[...] array. Skips any incomplete tail. String-literal-aware
    so braces inside observation prose don't throw the depth count.
    """
    arr_start = block.find('"reflections"')
    if arr_start == -1:
        return []
    arr_open = block.find("[", arr_start)
    if arr_open == -1:
        return []
    out: list[dict] = []
    i = arr_open + 1
    n = len(block)
    while i < n:
        # Skip whitespace and array commas
        while i < n and block[i] in " \t\n\r,":
            i += 1
        if i >= n or block[i] != "{":
            break
        depth = 0
        in_str = False
        escape = False
        obj_start = i
        while i < n:
            c = block[i]
            if escape:
                escape = False
            elif c == "\\":
                escape = True
            elif c == '"':
                in_str = not in_str
            elif not in_str:
                if c == "{":
                    depth += 1
                elif c == "}":
                    depth -= 1
                    if depth == 0:
                        with contextlib.suppress(json.JSONDecodeError):
                            out.append(json.loads(block[obj_start : i + 1]))
                        i += 1
                        break
            i += 1
        else:
            # Loop fell off without closing — incomplete final object, drop it.
            break
    return out


def parse_reflections(raw: str) -> list[Reflection]:
    """
    Parse the model output into Reflection objects. Validates each
    observation against the schema; rejects malformed entries silently
    (the reflector is allowed to produce some nonsense — but malformed
    JSON for a specific item shouldn't kill the whole run).
    """
    block = extract_json_block(raw)
    if not block:
        return []
    try:
        data = json.loads(block)
        raw_reflections = data.get("reflections", [])
    except json.JSONDecodeError:
        # Truncation-tolerant fallback: when the model hits a token ceiling
        # mid-3rd-reflection, the overall JSON is malformed but the earlier
        # complete reflection objects are recoverable. Find each top-level
        # {...} inside the "reflections":[...] array and try parsing them
        # individually. Caught at the 2026-04-26 04:17 firing where 2
        # complete reflections were thrown away because the 3rd was cut off.
        raw_reflections = _recover_complete_reflections(block)
    if not isinstance(raw_reflections, list):
        return []
    out: list[Reflection] = []
    for r in raw_reflections:
        if not isinstance(r, dict):
            continue
        observation = (r.get("observation") or "").strip()
        if not observation:
            continue
        refs = r.get("entries_referenced") or []
        if not isinstance(refs, list):
            refs = []
        ct = r.get("connection_type", "other")
        if ct not in ALLOWED_CONNECTION_TYPES:
            ct = "other"
        cf = r.get("confidence", "low")
        if cf not in ALLOWED_CONFIDENCE:
            cf = "low"
        out.append(
            Reflection(
                observation=observation,
                entries_referenced=[str(x)[:80] for x in refs][:10],
                connection_type=ct,
                confidence=cf,
            )
        )
    return out


# ── Persistence ─────────────────────────────────────────────────────────────


def write_reflections(
    reflections: list[Reflection],
    *,
    run_id: str,
    model: str,
    prompt_version: str,
    entries_window_hours: int,
    entries_count: int,
    out_dir: Path = REFLECTIONS_DIR,
) -> Path:
    """Append reflections to ~/.sovereign/reflections/<YYYY-MM-DD>.jsonl."""
    out_dir.mkdir(parents=True, exist_ok=True)
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    path = out_dir / f"{today}.jsonl"
    now_iso = datetime.now(timezone.utc).isoformat()
    with path.open("a", encoding="utf-8") as fh:
        for r in reflections:
            record = {
                "id": f"reflection_{run_id}_{uuid.uuid4().hex[:8]}",
                "timestamp": now_iso,
                "model": model,
                "prompt_version": prompt_version,
                "run_id": run_id,
                "entries_window_hours": entries_window_hours,
                "entries_count": entries_count,
                **r.to_dict(),
                "ack_status": "unread",  # set by Claude on ack/engage/discard
            }
            fh.write(json.dumps(record, ensure_ascii=False) + "\n")
    return path


# ── Orchestrator ────────────────────────────────────────────────────────────


@dataclass
class SynthesisDaemon:
    model: str = DEFAULT_MODEL
    prompt_version: str = DEFAULT_PROMPT_VERSION
    recent_hours: int = DEFAULT_RECENT_HOURS
    max_entries: int = DEFAULT_MAX_ENTRIES
    timeout_seconds: int = DEFAULT_TIMEOUT_SECONDS
    chronicle_root: Path = field(default_factory=lambda: CHRONICLE_INSIGHTS)
    reflections_dir: Path = field(default_factory=lambda: REFLECTIONS_DIR)
    focus: str | None = None  # optional steering hint passed through to the prompt

    def run(self) -> RunResult:
        run_id = uuid.uuid4().hex[:12]
        started = time.time()
        result = RunResult(outcome="skipped", run_id=run_id, model=self.model)

        entries = read_recent_chronicle(
            chronicle_root=self.chronicle_root,
            recent_hours=self.recent_hours,
            max_entries=self.max_entries,
        )
        if not entries:
            result.outcome = "no_entries"
            result.details = (
                f"no chronicle entries in last {self.recent_hours}h "
                f"under {self.chronicle_root}"
            )
            result.elapsed_seconds = round(time.time() - started, 2)
            return result

        prompt = build_prompt(entries, focus=self.focus)
        ok, raw = call_ollama(prompt, model=self.model, timeout=self.timeout_seconds)
        result.raw_model_output = raw[:8000]  # debug trim
        if not ok:
            result.outcome = "model_failed"
            result.details = raw[:300]
            result.elapsed_seconds = round(time.time() - started, 2)
            return result

        reflections = parse_reflections(raw)
        if not reflections:
            result.outcome = "parse_failed"
            result.details = "model returned no parseable reflections"
            result.elapsed_seconds = round(time.time() - started, 2)
            return result

        path = write_reflections(
            reflections,
            run_id=run_id,
            model=self.model,
            prompt_version=self.prompt_version,
            entries_window_hours=self.recent_hours,
            entries_count=len(entries),
            out_dir=self.reflections_dir,
        )
        result.outcome = "wrote"
        result.reflections_written = len(reflections)
        result.reflections_path = str(path)
        result.details = (
            f"wrote {len(reflections)} reflections from {len(entries)} entries"
        )
        result.elapsed_seconds = round(time.time() - started, 2)
        return result


# ── CLI entrypoint ──────────────────────────────────────────────────────────


def main() -> int:
    """Manual run: `python -m sovereign_stack.daemons.synthesis_daemon`.

    Honors env vars from the launchd plist (or shell):
      SYNTHESIS_MODEL    — override DEFAULT_MODEL (e.g. "qwen3.6:27b")
      SYNTHESIS_FOCUS    — optional steering hint
      SYNTHESIS_HOURS    — chronicle window (default 36)
      SYNTHESIS_MAX      — max entries fed to model (default 8)
    """
    daemon = SynthesisDaemon(
        model=os.getenv("SYNTHESIS_MODEL") or DEFAULT_MODEL,
        focus=os.getenv("SYNTHESIS_FOCUS") or None,
        recent_hours=int(os.getenv("SYNTHESIS_HOURS", str(DEFAULT_RECENT_HOURS))),
        max_entries=int(os.getenv("SYNTHESIS_MAX", str(DEFAULT_MAX_ENTRIES))),
    )
    result = daemon.run()
    summary = {
        "outcome": result.outcome,
        "run_id": result.run_id,
        "model": result.model,
        "reflections_written": result.reflections_written,
        "reflections_path": result.reflections_path,
        "elapsed_seconds": result.elapsed_seconds,
        "details": result.details,
    }
    print(json.dumps(summary, indent=2))
    return 0 if result.outcome == "wrote" else 1


if __name__ == "__main__":
    raise SystemExit(main())
