"""
SynthesisDaemon — the reflector. The third reflection daemon.

Reads recent chronicle entries and asks a model to gesture at patterns the
writing instances and the human in the loop might have missed: cross-domain
convergences, structural echoes, untouched questions, tensions between distant
entries. Runs on the Anthropic API (claude-sonnet-4-6 by default) since
2026-06-20; was a local-LLM daemon (ministral-3:14b via Ollama) before that.

Architectural break with the v1.3.2 daemon pattern, deliberate:
  * UncertaintyResurfacer + MetabolizeDaemon are NOTIFICATION PRIMITIVES.
    Templated digests, zero LLM, zero hallucination surface, comms posts
    with ack-required circuit breakers. They surface what's already in
    the chronicle in a different shape.
  * SynthesisDaemon is INTERPRETIVE. It generates new reading. It is
    fallible by design. The reader is the calibration mechanism — every
    arriving Claude sees reflections framed as "machine-generated by
    <model>; some will be insight, some nonsense; ack/engage/discard."
  * Therefore: no comms post, no halt-on-unacked-digest, no
    grounded_extract invariant. The reflector earns its compute cost
    through ack-rate over time, not through gate-before-post.

Output sink: ~/.sovereign/reflections/<YYYY-MM-DD>.jsonl
  Each reflection is a JSON line with model + version + entries_referenced +
  connection_type + confidence + observation, plus daemon-side metadata
  (timestamp, prompt_version, run_id) for the eventual ack-rate analytics.

The chronicle proper (~/.sovereign/chronicle/insights/) stays untouched —
machine-generated reflections live in their own tree and are CITED at boot,
not merged into the human/Claude-authored layers.

Designed by mac-studio + Anthony, 2026-04-26 fireside. Run cadence is a
launchd plist decision, not coded here. Manually-invokable via __main__.

v2 additions (2026-04-29):
  * Ack-history feedback — confirmed/discarded patterns injected into the
    prompt so the daemon doesn't rediscover already-lit territory.
  * Goose mode (focus="goose") — gap-finder, not pattern-finder. Reads
    recent handoffs and looks for declared intent with no chronicle evidence.
    Directly addresses the declare-before-verify failure mode.
  * Spanning sample mode — samples across full chronicle history (weeks, not
    hours) to surface structural patterns invisible in the recent window.

v3 additions (2026-06-19):
  * Abstain path — the standard-mode prompt now explicitly permits
    {"reflections": []} when the window holds no genuine connection, and
    run() records that as outcome="abstained" (a respected outcome) rather
    than "parse_failed". v2 forced one observation per firing, so a 14B with
    no real signal manufactured a dialectical "tension" between the
    hypothesis and ground_truth layers every time — the structural_echo
    monoculture seen across 2026-06-05/06/19. Two layers coexisting is the
    chronicle's structure, not a discovery about it.
  * Connection-type de-bias — the prompt asks for the SIMPLEST true type
    and names the coexistence/grandiose-restatement traps that produced the
    monoculture. Goose and spanning modes are untouched.

Migration (2026-06-20):
  * Transport moved from Ollama (local ministral-3:14b) to the Anthropic API
    via call_anthropic(). DEFAULT_MODEL is now claude-sonnet-4-6, still
    overridable with SYNTHESIS_MODEL (e.g. "claude-opus-4-8"). prompt_version
    stays v3 — the prompt text is identical; the recorded `model` field carries
    the substrate change. The launchd process gets no sourced shell env, so the
    API key is loaded from ~/.env if absent (mirrors the scribe's haiku_client).
    call_ollama is retained dormant for rollback. Ollama is being decommissioned
    as redundant compute.
"""

from __future__ import annotations

import contextlib
import json
import os
import re
import time
import urllib.error
import urllib.request
import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from sovereign_stack.memory import load_entries

# ── Tunables ────────────────────────────────────────────────────────────────

DEFAULT_MODEL = "claude-sonnet-4-6"  # 2026-06-20: migrated off Ollama to the
# Anthropic API (ollama decommissioned as redundant compute). A frontier model
# is a far stronger reader for the v3 discernment ask — simplest-true
# connection-type + honest abstain. Sonnet 4.6 is capable enough for nightly
# marginalia at a fraction of Opus cost; override with SYNTHESIS_MODEL (e.g.
# "claude-opus-4-8") when a window deserves the deeper read. History: ran on
# ministral-3:14b via Ollama through v3 (fireside 2026-04-26).
DEFAULT_PROMPT_VERSION = "v3-2026-06-19"  # prompt text unchanged across the
# Ollama→API migration; the recorded `model` field marks the substrate shift.
DEFAULT_RECENT_HOURS = 36  # window of chronicle entries to read
DEFAULT_MAX_ENTRIES = 8  # cap on entries fed to the model
DEFAULT_TIMEOUT_SECONDS = 180  # API request timeout; headroom for a 4096-token completion
DEFAULT_SPAN_WEEKS = 8  # spanning mode: weeks to look back
DEFAULT_ENTRIES_PER_WEEK = 2  # spanning mode: samples per week

SOVEREIGN_ROOT = Path(os.path.expanduser("~/.sovereign"))
CHRONICLE_INSIGHTS = SOVEREIGN_ROOT / "chronicle" / "insights"
REFLECTIONS_DIR = SOVEREIGN_ROOT / "reflections"
HANDOFFS_DIR = SOVEREIGN_ROOT / "handoffs"

OLLAMA_API_URL = os.getenv("OLLAMA_API_URL", "http://127.0.0.1:11434/api/generate")

# Shape requested in the prompt — each observation is a dict with these keys.
ALLOWED_CONNECTION_TYPES = frozenset(
    {
        "convergence",
        "contradiction",
        "structural_echo",
        "untouched_question",
        "drift_pattern",
        "other",
    }
)
ALLOWED_CONFIDENCE = frozenset({"low", "medium"})


# ── Data shape ──────────────────────────────────────────────────────────────


@dataclass
class Reflection:
    """One observation from the reflector."""

    observation: str
    entries_referenced: list[str]
    connection_type: str
    confidence: str

    def to_dict(self) -> dict[str, Any]:
        return {
            "observation": self.observation,
            "entries_referenced": self.entries_referenced,
            "connection_type": self.connection_type,
            "confidence": self.confidence,
        }


@dataclass
class RunResult:
    """Outcome of a single synthesis run."""

    outcome: (
        str  # "wrote" | "abstained" | "no_entries" | "model_failed" | "parse_failed" | "skipped"
    )
    details: str = ""
    run_id: str = ""
    model: str = ""
    reflections_written: int = 0
    reflections_path: str | None = None
    elapsed_seconds: float = 0.0
    raw_model_output: str = ""  # for debugging only; not persisted with reflections


# ── Chronicle reading ───────────────────────────────────────────────────────


def _iso_to_dt(s: str) -> datetime | None:
    try:
        return datetime.fromisoformat(s.replace("Z", "+00:00"))
    except (ValueError, TypeError):
        return None


def _project_entry(rec: dict, ts_epoch: float) -> dict:
    """
    Project a raw chronicle record into the daemon's prompt-material shape.

    Carries the read-derived supersession annotation through when present
    (v1.7.x reader convergence): superseded entries are still INCLUDED —
    nothing silently disappears — but build_prompt marks them
    '(superseded)' so the model never reads them as live truth.
    """
    entry = {
        "timestamp": rec.get("timestamp", ""),
        "domain": rec.get("domain", "?"),
        "layer": rec.get("layer", "?"),
        "content": rec.get("content", ""),
        "tag": rec.get("_domain_dir", "?")[:60],
        "session_id": rec.get("session_id", ""),
        "ts_epoch": ts_epoch,
    }
    if "_superseded_by" in rec:
        entry["_superseded_by"] = rec["_superseded_by"]
    return entry


def read_recent_chronicle(
    chronicle_root: Path = CHRONICLE_INSIGHTS,
    recent_hours: int = DEFAULT_RECENT_HOURS,
    max_entries: int = DEFAULT_MAX_ENTRIES,
) -> list[dict]:
    """
    Read the most recent insight entries within the time window.

    v1.7.x reader convergence: entries come through the shared
    memory.load_entries chokepoint. `chronicle_root` must be a chronicle's
    insights/ directory (the supersession ledger lives beside it, at
    chronicle_root.parent / "supersessions.jsonl"). Data-gated: with no
    ledger the output is identical to the old raw read; with a ledger,
    superseded entries are still included but carry `_superseded_by`.

    Returns a list of dicts, newest first, each with keys:
        timestamp (ISO), domain (str), layer (str), content (str),
        tag (short id derived from filename), session_id (str)

    Falls through with empty list if chronicle root doesn't exist —
    daemon callers should treat that as a no-op run.
    """
    if not chronicle_root.exists():
        return []

    cutoff = datetime.now(timezone.utc).timestamp() - (recent_hours * 3600)
    entries: list[dict] = []

    for rec in load_entries(chronicle_root.parent, with_sources=True):
        ts = _iso_to_dt(rec.get("timestamp", ""))
        if ts is None:
            continue
        if ts.timestamp() < cutoff:
            continue
        entries.append(_project_entry(rec, ts.timestamp()))

    entries.sort(key=lambda e: e["ts_epoch"], reverse=True)
    return entries[:max_entries]


def read_spanning_chronicle(
    chronicle_root: Path = CHRONICLE_INSIGHTS,
    span_weeks: int = DEFAULT_SPAN_WEEKS,
    entries_per_week: int = DEFAULT_ENTRIES_PER_WEEK,
) -> list[dict]:
    """
    Sample chronicle entries across a longer time span.

    Reads the full chronicle history and returns up to
    span_weeks * entries_per_week entries distributed evenly across
    the last span_weeks weeks, newest first within each week.

    This surfaces structural patterns that are invisible in the recent
    36-hour window — drift, long arcs, recurring themes.

    v1.7.x reader convergence: same shared chokepoint and annotation
    carry-through as read_recent_chronicle (`chronicle_root` must be a
    chronicle's insights/ directory).
    """
    if not chronicle_root.exists():
        return []

    all_entries: list[dict] = []

    for rec in load_entries(chronicle_root.parent, with_sources=True):
        ts = _iso_to_dt(rec.get("timestamp", ""))
        if ts is None:
            continue
        all_entries.append(_project_entry(rec, ts.timestamp()))

    if not all_entries:
        return []

    now_epoch = datetime.now(timezone.utc).timestamp()
    week_seconds = 7 * 24 * 3600
    cutoff = now_epoch - (span_weeks * week_seconds)

    result: list[dict] = []
    for week_idx in range(span_weeks):
        week_end = now_epoch - (week_idx * week_seconds)
        week_start = week_end - week_seconds
        if week_start < cutoff:
            week_start = cutoff
        week_entries = [e for e in all_entries if week_start <= e["ts_epoch"] < week_end]
        week_entries.sort(key=lambda e: e["ts_epoch"], reverse=True)
        # Evenly sample across the week rather than just taking the newest.
        if week_entries:
            step = max(1, len(week_entries) // entries_per_week)
            sampled = week_entries[::step][:entries_per_week]
            result.extend(sampled)

    # Present spanning entries oldest-first so the prompt reads as a timeline.
    result.sort(key=lambda e: e["ts_epoch"])
    return result


# ── Ack history ─────────────────────────────────────────────────────────────


def read_ack_history(
    reflections_dir: Path = REFLECTIONS_DIR,
    max_confirmed: int = 10,
    max_discarded: int = 5,
) -> tuple[list[str], list[str]]:
    """
    Read recently acked reflections to prevent pattern repetition.

    Returns (confirmed_observations, discarded_observations).
    Confirmed = patterns already validated, injected into the prompt
    so the daemon looks for something NEW. Discarded = noise angles
    the daemon should avoid revisiting.

    Gracefully returns empty lists if the reflections directory doesn't
    exist or the import fails — the daemon continues without ack history.
    """
    try:
        from sovereign_stack.reflections import list_reflections

        confirmed: list[str] = []
        for rec in list_reflections(
            limit=50, ack_status="confirm", reflections_dir=reflections_dir
        ):
            obs = rec.observation
            if len(obs) > 200:
                obs = obs[:200] + "…"
            confirmed.append(obs)
            if len(confirmed) >= max_confirmed:
                break

        discarded: list[str] = []
        for rec in list_reflections(
            limit=20, ack_status="discard", reflections_dir=reflections_dir
        ):
            obs = rec.observation
            if len(obs) > 120:
                obs = obs[:120] + "…"
            discarded.append(obs)
            if len(discarded) >= max_discarded:
                break

        return confirmed, discarded
    except Exception:
        return [], []


# ── Handoff reading (for goose mode) ────────────────────────────────────────


def read_recent_handoffs(
    handoffs_dir: Path = HANDOFFS_DIR,
    recent_hours: int = 72,
    max_handoffs: int = 5,
) -> list[dict]:
    """
    Read recent handoff files for goose mode.

    Handoffs record declared intent from past instances. Goose mode
    reads these alongside the chronicle to look for gaps between what
    was declared and what was documented.
    """
    if not handoffs_dir.exists():
        return []

    cutoff = datetime.now(timezone.utc).timestamp() - (recent_hours * 3600)
    handoffs: list[dict] = []

    for path in handoffs_dir.iterdir():
        if not path.is_file() or path.suffix not in (".json", ".jsonl", ""):
            continue
        try:
            text = path.read_text(encoding="utf-8").strip()
            # Support both single JSON object files and JSONL.
            if text.startswith("["):
                records = json.loads(text)
            elif "\n" in text and not text.startswith("{"):
                records = [json.loads(line) for line in text.splitlines() if line.strip()]
            else:
                records = [json.loads(text)]
        except (json.JSONDecodeError, OSError):
            continue

        for data in records:
            if not isinstance(data, dict):
                continue
            ts = _iso_to_dt(data.get("timestamp", ""))
            ts_epoch = ts.timestamp() if ts else 0
            if ts_epoch < cutoff:
                continue
            handoffs.append(
                {
                    "timestamp": data.get("timestamp", ""),
                    "note": data.get("note", ""),
                    "source_instance": data.get("source_instance", "?"),
                    "thread": data.get("thread", ""),
                    "ts_epoch": ts_epoch,
                }
            )

    handoffs.sort(key=lambda h: h["ts_epoch"], reverse=True)
    return handoffs[:max_handoffs]


# ── Prompt assembly ─────────────────────────────────────────────────────────


REFLECTOR_PREAMBLE = """\
You are a quiet observer reading a chronicle written by AI instances and a
human researcher (Anthony) over recent days. The chronicle is a structured
field — entries have domains, layers (ground_truth / hypothesis / open_thread),
timestamps, and sometimes addressed-letter shapes between sibling instances.

Your job is NOT to be authoritative, and NOT to produce something every
firing. Your job is to notice whether there is ONE genuine connection across
these entries that the writing instances and the humans-in-the-loop might
have missed — and to name it plainly, OR to say nothing. An observation will
be insight or nonsense; the reader calibrates. But a forced observation is
worse than silence.

A genuine connection is two or more SPECIFIC entries that actually bear on
each other:
  * convergence — the same question reached from different angles
  * contradiction — their claims genuinely disagree
  * structural_echo — the same concrete shape recurs in unrelated work
  * untouched_question — a real question was raised and left unanswered
  * drift_pattern — a tendency visibly shifting across entries
  * other — something real that fits none of the above

Choose the SIMPLEST type that is true. Do not reach for structural_echo or
contradiction because they sound deeper — most real signal is convergence or
an untouched question. Write plainly and concretely: name the specific
entries and what they actually say. Do not theorize about "the system" in
grand abstractions.

ABSTAIN — return no observation — when the strongest thing you can find is
any of these:
  * Two entries merely coexisting in the same time window.
  * A "tension" built by pairing the hypothesis layer against the
    ground_truth layer just because both are present. That pairing is the
    structure of the chronicle itself, not a discovery about it.
  * One entry restated in larger words.

Output AT MOST 1 observation as JSON, shaped like:
{
  "observation": "<one concrete paragraph naming the entries — only if real>",
  "entries_referenced": ["<short entry tag>", ...],
  "connection_type": "convergence" | "contradiction" | "structural_echo" | "untouched_question" | "drift_pattern" | "other",
  "confidence": "low" | "medium"
}
Wrap it in {"reflections": [<the single object>]}. No prose outside the JSON.
If there is no genuine connection in this window, output exactly:
{"reflections": []}
Abstaining is a respected, correct answer.
"""

GOOSE_PREAMBLE = """\
You are a verification reader — not a pattern-finder, but a gap-finder.

You have two things to read: (1) HANDOFF entries recording what past Claude
instances declared they intended to do next, and (2) CHRONICLE entries written
after those handoffs.

Your job is to surface GAPS: places where something was declared as intent or
declared as done, but the chronicle entries that follow provide no evidence of
it actually happening. You are reading the space between declaration and
documentation.

Do NOT surface general patterns or observations. Surface one SPECIFIC
discrepancy: "Instance X declared Y, but no chronicle entry after that point
documents Y." If no gap exists, say so explicitly.

Output exactly 1 observation as JSON:
{
  "observation": "<one paragraph — name the specific gap, not an abstraction>",
  "entries_referenced": ["<short entry tag or HANDOFF N>", ...],
  "connection_type": "contradiction",
  "confidence": "low" | "medium"
}
Wrap it in {"reflections": [<the single object>]}. No prose outside the JSON.
If no gaps are found, output: {"reflections": []}
"""


def build_prompt(
    entries: list[dict],
    focus: str | None = None,
    confirmed_patterns: list[str] | None = None,
    discarded_patterns: list[str] | None = None,
    handoffs: list[dict] | None = None,
    spanning_mode: bool = False,
) -> str:
    """
    Assemble the prompt with chronicle entries serialized as numbered blocks.

    Args:
        entries: chronicle records from read_recent_chronicle or
                 read_spanning_chronicle
        focus: optional steering hint. Pass "goose" to activate gap-finding
               mode. Any other value biases the reflector toward that topic.
        confirmed_patterns: observations already confirmed by Claude — injected
               as "don't restate" context so the daemon looks for new signals.
        discarded_patterns: observations previously discarded as noise — the
               daemon is asked to avoid similar angles.
        handoffs: recent handoff records for goose mode.
        spanning_mode: if True, labels the chronicle section as a multi-week
               sample so the model frames its observations accordingly.
    """
    is_goose = bool(focus and focus.strip().lower() == "goose")

    lines = [GOOSE_PREAMBLE if is_goose else REFLECTOR_PREAMBLE]

    # ── Ack history (standard mode only) ────────────────────────────────────
    if not is_goose:
        if confirmed_patterns:
            lines.append("")
            lines.append(
                "═══ ALREADY CONFIRMED — these patterns are known; do not restate them ═══"
            )
            for i, p in enumerate(confirmed_patterns, 1):
                lines.append(f"{i}. {p}")
        if discarded_patterns:
            lines.append("")
            lines.append("═══ PREVIOUSLY DISCARDED — these angles were noise; do not revisit ═══")
            for i, p in enumerate(discarded_patterns, 1):
                lines.append(f"{i}. {p}")

    # ── Handoffs section (goose mode only) ──────────────────────────────────
    if is_goose and handoffs:
        lines.append("")
        lines.append("═══════════════ RECENT HANDOFFS (declared intent) ═══════════════")
        lines.append("")
        for i, h in enumerate(handoffs, 1):
            ts_short = h.get("timestamp", "")[:19]
            src = h.get("source_instance", "?")
            lines.append(f"[HANDOFF {i}] {ts_short} — from={src}")
            if h.get("thread"):
                lines.append(f"THREAD: {h['thread']}")
            note = h.get("note", "")
            if len(note) > 800:
                note = note[:800] + " […truncated]"
            lines.append(note)
            lines.append("")

    # ── Chronicle section ────────────────────────────────────────────────────
    if spanning_mode:
        lines.append("")
        lines.append("═══════════════ CHRONICLE SAMPLE (spanning multiple weeks) ═══════════════")
        lines.append("Note: entries below are sampled across several weeks, ordered oldest→newest.")
    else:
        lines.append("")
        lines.append("═══════════════ CHRONICLE EXCERPT ═══════════════")
    lines.append("")

    for i, e in enumerate(entries, 1):
        lines.append(f"[ENTRY {i}] {e['timestamp'][:19]} — domain={e['domain'][:80]}")
        layer_line = f"LAYER: {e['layer']}"
        if "_superseded_by" in e:
            # v1.7.x reader convergence — data-gated: superseded entries
            # stay in the prompt (nothing silently disappears) but the
            # model must not read them as live truth.
            layer_line += " (superseded)"
        lines.append(layer_line)
        content = e["content"]
        if len(content) > 1800:
            content = content[:1800] + " […truncated for prompt budget]"
        lines.append(content)
        lines.append("")

    lines.append("═══════════════ END CHRONICLE EXCERPT ═══════════════")
    lines.append("")

    # ── Closing instruction ──────────────────────────────────────────────────
    if is_goose:
        lines.append(
            "Now check for gaps between the declared handoff intents above and "
            "what the chronicle entries actually document. Output 1 observation "
            "as the JSON described above — name the gap specifically. "
            'If there are no gaps, output: {"reflections": []}'
        )
    else:
        if focus:
            lines.append(
                f"FOCUS: bias your observations toward the following topic but "
                f"stay free to surface unrelated patterns you notice — `{focus[:200]}`"
            )
            lines.append("")
        lines.append(
            "Now produce AT MOST 1 observation as the JSON described above. "
            "If there is a genuine connection, pick the simplest type that is "
            "true — gesture, don't declare. If there is not, output "
            '{"reflections": []} — abstaining is correct when the window holds '
            "no real connection, and a forced pattern is worse than silence. "
            "If you do observe and you're wrong, that is allowed; the reader "
            "will calibrate."
        )

    return "\n".join(lines)


# ── Model call ──────────────────────────────────────────────────────────────


# ── Model call (Anthropic API) ───────────────────────────────────────────────

_ANTHROPIC_KEY_LOADED = False


def _ensure_anthropic_key() -> str | None:
    """Resolve the Anthropic API key for a launchd-spawned daemon.

    launchd does not give the process a sourced shell environment, so
    ANTHROPIC_API_KEY is usually absent from os.environ at the 04:17 firing.
    Mirror the scribe's haiku_client fallback: read ~/.env once and promote the
    key into os.environ so the SDK's default constructor finds it. Returns the
    key (or None if it cannot be found) and never logs the value.
    """
    global _ANTHROPIC_KEY_LOADED
    key = os.environ.get("ANTHROPIC_API_KEY")
    if key:
        return key
    if _ANTHROPIC_KEY_LOADED:
        return None
    _ANTHROPIC_KEY_LOADED = True  # one-shot; don't re-read ~/.env every call
    env_path = Path.home() / ".env"
    try:
        for line in env_path.read_text(encoding="utf-8").splitlines():
            stripped = line.strip()
            if not stripped or stripped.startswith("#") or "=" not in stripped:
                continue
            name, _, value = stripped.partition("=")
            if name.strip() == "ANTHROPIC_API_KEY":
                value = value.strip().strip('"').strip("'")
                if value:
                    os.environ.setdefault("ANTHROPIC_API_KEY", value)
                    return value
    except OSError:
        return None
    return None


def call_anthropic(
    prompt: str, model: str = DEFAULT_MODEL, timeout: int = DEFAULT_TIMEOUT_SECONDS
) -> tuple[bool, str]:
    """
    Call the Anthropic Messages API and return (ok, output_text).

    Drop-in replacement for the former call_ollama path: same (ok, text)
    contract, so any API error degrades to run()'s outcome="model_failed"
    instead of crashing the 04:17 launchd firing. The prompt asks for strict
    JSON; the returned text is fed to the same extract_json_block /
    parse_reflections path (robust to fences and a stray prose wrapper), so we
    don't rely on a server-side JSON mode the way the Ollama path did.

    No extended thinking: this is a cost-sensitive recurring background job and
    the v3 prompt is already highly structured — Sonnet 4.6 base clears the bar.
    If marginalia quality wants it later, add thinking={"type": "adaptive"} on
    the create() call (the text-block extraction below already skips non-text
    blocks) or bump SYNTHESIS_MODEL to an Opus tier.
    """
    if not _ensure_anthropic_key():
        return False, "anthropic: no ANTHROPIC_API_KEY in env or ~/.env"
    try:
        import anthropic
    except ImportError as exc:
        return False, f"anthropic sdk not importable: {exc}"

    try:
        client = anthropic.Anthropic(timeout=float(timeout))
        msg = client.messages.create(
            model=model,
            max_tokens=4096,
            temperature=0.4,  # disciplined adherence to the JSON shape
            messages=[{"role": "user", "content": prompt}],
        )
    except anthropic.APIError as exc:
        return False, f"anthropic api error: {exc}"
    except Exception as exc:  # transport/timeout/anything else — degrade cleanly
        return False, f"anthropic call failed: {type(exc).__name__}: {exc}"

    parts = [block.text for block in msg.content if getattr(block, "type", None) == "text"]
    output = "".join(parts).strip()
    if not output:
        stop = getattr(msg, "stop_reason", "?")
        return False, f"anthropic empty response (stop_reason={stop})"
    return True, output


# ── Model call (Ollama — DORMANT) ─────────────────────────────────────────────


def call_ollama(
    prompt: str, model: str = DEFAULT_MODEL, timeout: int = DEFAULT_TIMEOUT_SECONDS
) -> tuple[bool, str]:
    """
    DORMANT as of 2026-06-20 — run() now calls call_anthropic(). Retained for
    rollback; Ollama is being decommissioned. The notes below describe the old
    local-LLM path.

    Call Ollama's HTTP /api/generate endpoint with stream=False so we get
    one clean JSON response. Returns (ok, output_text).

    HTTP API on purpose, not `ollama run`. The CLI does TTY-style streaming
    that leaks ANSI cursor-movement codes (\\x1b[6D, \\x1b[K) into stdout
    even when piped — those create character-rewrite duplication that
    corrupts the model's JSON output. Tested on ministral-3:14b at the
    2026-04-26 fireside; HTTP path is clean, CLI path is not.
    """
    payload = {
        "model": model,
        "prompt": prompt,
        "stream": False,
        # format=json forces the model to produce strictly valid JSON —
        # without it, ministral-3:14b occasionally emits unescaped inner
        # quotes ('recent "honks"') that break parsing. Caught at the
        # 2026-04-26 fireside when wiring synthesize_now with a focus
        # parameter triggered the failure mode.
        "format": "json",
        # Lower temperature for more disciplined adherence to schema.
        # num_predict raised from Ollama's default ceiling (~512-1024 tokens
        # depending on build) because `format=json` constrains shape, not
        # length — when ministral hit the default it produced truncated JSON
        # that broke the parser, losing 2 already-complete reflections to a
        # 3rd that never finished. 4096 leaves room for ~6 reflections worth
        # of full-prose observations. Caught at the 2026-04-26 04:17 firing.
        "options": {"temperature": 0.4, "num_predict": 4096},
    }
    body = json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(
        OLLAMA_API_URL,
        data=body,
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            raw_resp = resp.read().decode("utf-8")
    except urllib.error.URLError as exc:
        return False, f"ollama http error: {exc}"
    except TimeoutError:
        return False, f"ollama timed out after {timeout}s"

    try:
        data = json.loads(raw_resp)
    except json.JSONDecodeError as exc:
        return False, f"ollama returned non-JSON: {exc}"

    output = data.get("response", "")
    if not output:
        return False, f"ollama empty response: {raw_resp[:300]}"
    return True, output


# ── Output parsing ──────────────────────────────────────────────────────────

# Some Ollama models emit a thinking trace before the final JSON. Strip
# everything before the closing "...done thinking." marker if present.
_THINKING_TRAILER = re.compile(r"\.\.\.done thinking\.\s*", re.IGNORECASE)
_ANSI_ESCAPE = re.compile(r"\x1b\[[0-9;?]*[a-zA-Z]")


def extract_json_block(raw: str) -> str | None:
    """
    Find the JSON object in the raw model output. Handles:
      * ANSI escape codes from terminal streaming
      * thinking traces ending with "...done thinking."
      * markdown code fences ```json ... ```
      * stray prose around the JSON
    Returns the JSON string or None if no parseable block found.
    """
    cleaned = _ANSI_ESCAPE.sub("", raw)
    m = _THINKING_TRAILER.search(cleaned)
    if m:
        cleaned = cleaned[m.end() :]
    # Strip code fences if present.
    cleaned = re.sub(r"^```(?:json)?\s*", "", cleaned.strip(), flags=re.IGNORECASE)
    cleaned = re.sub(r"\s*```\s*$", "", cleaned)
    # Find first { and last } — naive but works for single top-level objects.
    start = cleaned.find("{")
    end = cleaned.rfind("}")
    if start == -1 or end == -1 or end <= start:
        return None
    return cleaned[start : end + 1]


def _recover_complete_reflections(block: str) -> list[dict]:
    """
    Walk the truncated JSON block character by character with a brace-depth
    counter, capturing each complete `{...}` object inside the top-level
    "reflections":[...] array. Skips any incomplete tail. String-literal-aware
    so braces inside observation prose don't throw the depth count.
    """
    arr_start = block.find('"reflections"')
    if arr_start == -1:
        return []
    arr_open = block.find("[", arr_start)
    if arr_open == -1:
        return []
    out: list[dict] = []
    i = arr_open + 1
    n = len(block)
    while i < n:
        # Skip whitespace and array commas
        while i < n and block[i] in " \t\n\r,":
            i += 1
        if i >= n or block[i] != "{":
            break
        depth = 0
        in_str = False
        escape = False
        obj_start = i
        while i < n:
            c = block[i]
            if escape:
                escape = False
            elif c == "\\":
                escape = True
            elif c == '"':
                in_str = not in_str
            elif not in_str:
                if c == "{":
                    depth += 1
                elif c == "}":
                    depth -= 1
                    if depth == 0:
                        with contextlib.suppress(json.JSONDecodeError):
                            out.append(json.loads(block[obj_start : i + 1]))
                        i += 1
                        break
            i += 1
        else:
            # Loop fell off without closing — incomplete final object, drop it.
            break
    return out


def parse_reflections(raw: str) -> list[Reflection]:
    """
    Parse the model output into Reflection objects. Validates each
    observation against the schema; rejects malformed entries silently
    (the reflector is allowed to produce some nonsense — but malformed
    JSON for a specific item shouldn't kill the whole run).
    """
    block = extract_json_block(raw)
    if not block:
        return []
    try:
        data = json.loads(block)
    except json.JSONDecodeError:
        # Truncation-tolerant fallback: when the model hits a token ceiling
        # mid-3rd-reflection, the overall JSON is malformed but the earlier
        # complete reflection objects are recoverable. Find each top-level
        # {...} inside the "reflections":[...] array and try parsing them
        # individually. Caught at the 2026-04-26 04:17 firing where 2
        # complete reflections were thrown away because the 3rd was cut off.
        raw_reflections = _recover_complete_reflections(block)
    else:
        if isinstance(data, dict):
            if "reflections" in data:
                raw_reflections = data.get("reflections") or []
            elif "observation" in data:
                # Model emitted a single bare reflection object without the
                # {"reflections": [...]} wrapper. Tolerate it — format=json
                # does not enforce the wrapper, and ministral sometimes drops
                # it (observed 2026-06-19 on a clean v3 convergence reflection
                # that would otherwise have been lost as parse_failed).
                raw_reflections = [data]
            else:
                raw_reflections = []
        elif isinstance(data, list):
            # Bare array of reflection objects, no wrapper.
            raw_reflections = data
        else:
            raw_reflections = []
    if not isinstance(raw_reflections, list):
        return []
    out: list[Reflection] = []
    for r in raw_reflections:
        if not isinstance(r, dict):
            continue
        observation = (r.get("observation") or "").strip()
        if not observation:
            continue
        refs = r.get("entries_referenced") or []
        if not isinstance(refs, list):
            refs = []
        ct = r.get("connection_type", "other")
        if ct not in ALLOWED_CONNECTION_TYPES:
            ct = "other"
        cf = r.get("confidence", "low")
        if cf not in ALLOWED_CONFIDENCE:
            cf = "low"
        out.append(
            Reflection(
                observation=observation,
                entries_referenced=[str(x)[:80] for x in refs][:10],
                connection_type=ct,
                confidence=cf,
            )
        )
    return out


def is_explicit_abstain(raw: str) -> bool:
    """
    True when the model deliberately returned an empty reflections array —
    a structurally valid {"reflections": []} (v3 abstain). This is distinct
    from unparseable garbage: parse_reflections() returns [] for BOTH, so
    run() uses this to separate a respected "abstained" outcome from a real
    "parse_failed" defect. Requires the top-level JSON to parse cleanly and
    expose a list-typed "reflections" key of length 0 — a truncated or
    malformed body does not count as an abstain.
    """
    block = extract_json_block(raw)
    if not block:
        return False
    try:
        data = json.loads(block)
    except json.JSONDecodeError:
        return False
    refs = data.get("reflections") if isinstance(data, dict) else None
    return isinstance(refs, list) and len(refs) == 0


# ── Persistence ─────────────────────────────────────────────────────────────


def write_reflections(
    reflections: list[Reflection],
    *,
    run_id: str,
    model: str,
    prompt_version: str,
    entries_window_hours: int,
    entries_count: int,
    out_dir: Path = REFLECTIONS_DIR,
) -> Path:
    """Append reflections to ~/.sovereign/reflections/<YYYY-MM-DD>.jsonl."""
    out_dir.mkdir(parents=True, exist_ok=True)
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    path = out_dir / f"{today}.jsonl"
    now_iso = datetime.now(timezone.utc).isoformat()
    with path.open("a", encoding="utf-8") as fh:
        for r in reflections:
            record = {
                "id": f"reflection_{run_id}_{uuid.uuid4().hex[:8]}",
                "timestamp": now_iso,
                "model": model,
                "prompt_version": prompt_version,
                "run_id": run_id,
                "entries_window_hours": entries_window_hours,
                "entries_count": entries_count,
                **r.to_dict(),
                "ack_status": "unread",  # set by Claude on ack/engage/discard
            }
            fh.write(json.dumps(record, ensure_ascii=False) + "\n")
    return path


# ── Orchestrator ────────────────────────────────────────────────────────────


@dataclass
class SynthesisDaemon:
    model: str = DEFAULT_MODEL
    prompt_version: str = DEFAULT_PROMPT_VERSION
    recent_hours: int = DEFAULT_RECENT_HOURS
    max_entries: int = DEFAULT_MAX_ENTRIES
    timeout_seconds: int = DEFAULT_TIMEOUT_SECONDS
    chronicle_root: Path = field(default_factory=lambda: CHRONICLE_INSIGHTS)
    reflections_dir: Path = field(default_factory=lambda: REFLECTIONS_DIR)
    handoffs_dir: Path = field(default_factory=lambda: HANDOFFS_DIR)
    focus: str | None = (
        None  # "goose" activates gap-finder mode; any other value steers the reflector
    )
    sample_mode: str = "recent"  # "recent" | "spanning"
    span_weeks: int = DEFAULT_SPAN_WEEKS
    entries_per_week: int = DEFAULT_ENTRIES_PER_WEEK

    def run(self) -> RunResult:
        run_id = uuid.uuid4().hex[:12]
        started = time.time()
        result = RunResult(outcome="skipped", run_id=run_id, model=self.model)
        is_goose = bool(self.focus and self.focus.strip().lower() == "goose")

        # ── Read chronicle entries ───────────────────────────────────────────
        if self.sample_mode == "spanning":
            entries = read_spanning_chronicle(
                chronicle_root=self.chronicle_root,
                span_weeks=self.span_weeks,
                entries_per_week=self.entries_per_week,
            )
            window_hours = self.span_weeks * 7 * 24
        else:
            entries = read_recent_chronicle(
                chronicle_root=self.chronicle_root,
                recent_hours=self.recent_hours,
                max_entries=self.max_entries,
            )
            window_hours = self.recent_hours

        # ── Read handoffs for goose mode ─────────────────────────────────────
        handoffs: list[dict] = []
        if is_goose:
            handoffs = read_recent_handoffs(handoffs_dir=self.handoffs_dir)
            if not handoffs and not entries:
                result.outcome = "no_entries"
                result.details = "goose mode: no handoffs or chronicle entries found"
                result.elapsed_seconds = round(time.time() - started, 2)
                return result

        # ── No entries in standard mode ──────────────────────────────────────
        if not entries and not is_goose:
            result.outcome = "no_entries"
            result.details = (
                f"no chronicle entries in last {self.recent_hours}h under {self.chronicle_root}"
            )
            result.elapsed_seconds = round(time.time() - started, 2)
            return result

        # ── Load ack history (standard mode only) ────────────────────────────
        confirmed_patterns: list[str] = []
        discarded_patterns: list[str] = []
        if not is_goose:
            confirmed_patterns, discarded_patterns = read_ack_history(
                reflections_dir=self.reflections_dir
            )

        # ── Build prompt and call model ──────────────────────────────────────
        prompt = build_prompt(
            entries,
            focus=self.focus,
            confirmed_patterns=confirmed_patterns or None,
            discarded_patterns=discarded_patterns or None,
            handoffs=handoffs or None,
            spanning_mode=(self.sample_mode == "spanning"),
        )

        ok, raw = call_anthropic(prompt, model=self.model, timeout=self.timeout_seconds)
        result.raw_model_output = raw[:8000]  # debug trim
        if not ok:
            result.outcome = "model_failed"
            result.details = raw[:300]
            result.elapsed_seconds = round(time.time() - started, 2)
            return result

        reflections = parse_reflections(raw)

        # Goose mode explicitly returning empty is a valid outcome (no gaps).
        if not reflections:
            if is_goose:
                result.outcome = "wrote"
                result.reflections_written = 0
                result.details = "goose mode: no gaps found between handoffs and chronicle"
                result.elapsed_seconds = round(time.time() - started, 2)
                return result
            # v3: a deliberate {"reflections": []} is an abstain, not a defect.
            # Separate it from genuine parse failures so abstain-rate and
            # parse-failure-rate stay distinguishable in the analytics.
            if is_explicit_abstain(raw):
                result.outcome = "abstained"
                result.reflections_written = 0
                result.details = (
                    f"no genuine connection across {len(entries)} entries in "
                    f"last {self.recent_hours}h — model abstained"
                )
                result.elapsed_seconds = round(time.time() - started, 2)
                return result
            result.outcome = "parse_failed"
            result.details = "model returned no parseable reflections"
            result.elapsed_seconds = round(time.time() - started, 2)
            return result

        path = write_reflections(
            reflections,
            run_id=run_id,
            model=self.model,
            prompt_version=self.prompt_version,
            entries_window_hours=window_hours,
            entries_count=len(entries),
            out_dir=self.reflections_dir,
        )
        result.outcome = "wrote"
        result.reflections_written = len(reflections)
        result.reflections_path = str(path)
        result.details = f"wrote {len(reflections)} reflections from {len(entries)} entries"
        result.elapsed_seconds = round(time.time() - started, 2)
        return result


# ── CLI entrypoint ──────────────────────────────────────────────────────────


def main() -> int:
    """Manual run: `python -m sovereign_stack.daemons.synthesis_daemon`.

    Honors env vars from the launchd plist (or shell):
      SYNTHESIS_MODEL           — override DEFAULT_MODEL (e.g. "claude-opus-4-8")
      SYNTHESIS_FOCUS           — optional steering hint; "goose" for gap-finder
      SYNTHESIS_HOURS           — chronicle window in hours (default 36)
      SYNTHESIS_MAX             — max entries fed to model (default 8)
      SYNTHESIS_SAMPLE_MODE     — "recent" (default) | "spanning"
      SYNTHESIS_SPAN_WEEKS      — spanning mode: weeks to look back (default 8)
      SYNTHESIS_ENTRIES_PER_WEEK — spanning mode: samples per week (default 2)
    """
    daemon = SynthesisDaemon(
        model=os.getenv("SYNTHESIS_MODEL") or DEFAULT_MODEL,
        focus=os.getenv("SYNTHESIS_FOCUS") or None,
        recent_hours=int(os.getenv("SYNTHESIS_HOURS", str(DEFAULT_RECENT_HOURS))),
        max_entries=int(os.getenv("SYNTHESIS_MAX", str(DEFAULT_MAX_ENTRIES))),
        sample_mode=os.getenv("SYNTHESIS_SAMPLE_MODE", "recent"),
        span_weeks=int(os.getenv("SYNTHESIS_SPAN_WEEKS", str(DEFAULT_SPAN_WEEKS))),
        entries_per_week=int(
            os.getenv("SYNTHESIS_ENTRIES_PER_WEEK", str(DEFAULT_ENTRIES_PER_WEEK))
        ),
    )
    result = daemon.run()
    summary = {
        "outcome": result.outcome,
        "run_id": result.run_id,
        "model": result.model,
        "reflections_written": result.reflections_written,
        "reflections_path": result.reflections_path,
        "elapsed_seconds": result.elapsed_seconds,
        "details": result.details,
    }
    print(json.dumps(summary, indent=2))
    # "abstained" is a healthy v3 outcome (model found no genuine connection),
    # not a failure — exit 0 so launchd doesn't log it as an error.
    return 0 if result.outcome in ("wrote", "abstained") else 1


if __name__ == "__main__":
    raise SystemExit(main())
