"""
Executable self-description.

WHY THIS EXISTS
---------------
On 2026-08-25 four architectures read this repository's public face and
came away with a self-portrait that contradicted itself: the header said
v1.15.0 / 97 tools, a module section said "v1.5.1 - 82 tools", and a
status block said 82 tools / 968 tests. One of them concluded from the
drift that a law which is live in production was unshipped, and built a
sequencing argument on it.

The counts were hand-maintained, which is the whole bug. A number typed
by a person is an assertion; a number derived from the running registry
is a projection. This module produces the projection, and CI refuses to
call the documentation current when the prose disagrees with it.

THE RULE IT ENFORCES, and it is the house's own as-of doctrine applied
to its README:

    A COUNT WITHOUT AN AS-OF IS DRIFT. A COUNT WITH AN AS-OF IS HISTORY.

Current counts live in exactly one place: the generated block. Anywhere
else in the document a count may appear only if its own line carries an
explicit `(as of ...)`, which turns a rotting claim into a dated one.

WHAT THIS CHECK DOES NOT COVER, stated because a silent gap in a drift
checker is the same disease one layer up:

    It enforces COUNTS, not VERSION LABELS.

`### Breath architecture (v1.5.0 - the fast lung)` means "introduced in
v1.5.0" and is timeless-true; `## Operations (v1.5.1 - ...)` reads as a
claim about the CURRENT version and rots. A regex cannot tell those two
apart, and a rule that flagged both would produce noise that trains
people to ignore the gate - which is worse than the drift it catches.
So version labels are a human judgement, and the one rotting instance
(line 125, found by the Fable seat 2026-08-26) was dated by hand rather
than by rule. If a later seat finds a second one, that is evidence the
judgement does not scale and the rule should be revisited - not evidence
that this note was wrong.

FAILS CLOSED, in three specific ways, because a manifest generator that
degrades quietly is worse than none - it launders staleness as coverage:
  * An empty tool registry raises. It never emits an empty manifest.
  * A README that asserts no current count at all raises, because then
    the check would be vacuous and would pass by having nothing to say.
  * An unparseable version raises rather than defaulting.
"""

from __future__ import annotations

import json
import re
import subprocess
from pathlib import Path

MANIFEST_SCHEMA_VERSION = 1
BEGIN_MARK = "<!-- MANIFEST:BEGIN - generated by sovereign_stack.manifest; do not hand-edit -->"
END_MARK = "<!-- MANIFEST:END -->"

# A count claim: "97 tools", "1,918+ tests". The optional "+" makes it a
# floor rather than an equality, and the checker honours that difference
# because the prose does.
_COUNT_RE = re.compile(r"(?<![\w.])(\d[\d,]*)(\+?)\s+(tools|tests)\b")
# Badge URLs hide their counts behind URL-encoding: `tests-1918%20passing`
# never matches `\d+ tests`. The checker policed the prose for a day while
# the headline badges rotted, which is why this pattern exists.
_BADGE_RE = re.compile(r"img\.shields\.io/badge/(?:version|tools|tests)-([\d.,]+)", re.IGNORECASE)
_AS_OF_RE = re.compile(r"\bas of\s+\S", re.IGNORECASE)
_VERSION_RE = re.compile(r'^version\s*=\s*"([^"]+)"', re.MULTILINE)


class ManifestError(RuntimeError):
    """Raised when the manifest cannot be built or checked honestly."""


def _git(*args: str, cwd: Path) -> str:
    try:
        out = subprocess.run(["git", *args], cwd=cwd, capture_output=True, text=True, timeout=15)
    except (OSError, subprocess.SubprocessError) as exc:  # pragma: no cover - env
        raise ManifestError(f"git {' '.join(args)} failed: {exc}") from exc
    return out.stdout.strip()


def live_tool_names() -> list[str]:
    """
    The registry, from the same function the server serves.

    Not a hand-kept list, not a grep over decorators - the actual
    coroutine MCP clients call. If this returns nothing, something is
    badly wrong and the caller must not paper over it.
    """
    import asyncio

    from sovereign_stack.server import list_tools

    tools = asyncio.run(list_tools())
    names = [t.name for t in tools]
    if not names:
        raise ManifestError(
            "live tool registry is EMPTY - refusing to emit a manifest. "
            "An empty manifest would read as 'zero tools, verified'."
        )
    return names


def build_manifest(*, repo_root: Path | None = None, tests_collected: int | None = None) -> dict:
    """Project the running system into a dict. Raises rather than guessing."""
    root = repo_root or Path(__file__).resolve().parents[2]
    pyproject = (root / "pyproject.toml").read_text(encoding="utf-8")
    m = _VERSION_RE.search(pyproject)
    if not m:
        raise ManifestError("could not parse version from pyproject.toml")

    names = sorted(live_tool_names())
    if not names:
        # Defense in depth. live_tool_names() already refuses to return an
        # empty registry, but this function must not depend on a helper's
        # guard to stay honest — found by the test that asserts this raises.
        raise ManifestError(
            "refusing to build a manifest from an empty registry - it would "
            "read as 'zero tools, verified'"
        )
    dirty = bool(_git("status", "--porcelain", cwd=root))
    return {
        "manifest_schema_version": MANIFEST_SCHEMA_VERSION,
        "version": m.group(1),
        "source_commit": _git("rev-parse", "HEAD", cwd=root),
        "working_tree_dirty": dirty,
        "tools_count": len(names),
        "tools": names,
        "tests_collected": tests_collected,
    }


def render_block(manifest: dict) -> str:
    """
    The one place in the README where a current count may live.

    Deliberately carries ONLY what is derivable from the registry and
    pyproject — version and tool count. The test count lives in
    stack_manifest.json instead, because rendering it here made the
    check's verdict depend on whether the caller happened to pass one:
    the same README would pass or fail based on the caller's argument,
    which is a gate with a mood rather than a rule.

    The BADGES live here too, as of 2026-08-26, and that was the sharper
    hole: the header badges read `tests-1918%20passing` and
    `version-1.15.0`, which are hand-typed counts in the most-read line
    of the repository — and URL-encoding made them INVISIBLE to the drift
    check, so the checker was policing the prose while the headline
    rotted. Version and tool badges are now generated. The test badge is
    gone entirely, replaced in the README by a live CI status badge that
    cannot drift because nobody types it.
    """
    ver, tools = manifest["version"], manifest["tools_count"]
    badges = (
        f"![Version](https://img.shields.io/badge/version-{ver}-purple) "
        f"![Tools](https://img.shields.io/badge/tools-{tools}-orange)"
    )
    return "\n".join(
        [
            BEGIN_MARK,
            "",
            badges,
            "",
            f"**v{ver} · {tools} tools**",
            "",
            "_Generated from the live tool registry. Every current count in this "
            "document lives here and nowhere else; a count elsewhere must carry "
            "its own `(as of ...)` or CI fails._",
            "",
            END_MARK,
        ]
    )


def _strip_generated_block(readme: str) -> str:
    if BEGIN_MARK in readme and END_MARK in readme:
        head, rest = readme.split(BEGIN_MARK, 1)
        _, tail = rest.split(END_MARK, 1)
        return head + tail
    return readme


def check_docs_against_manifest(manifest: dict, readme: str, pyproject: str) -> list[str]:
    """
    Return every disagreement between the prose and the projection.

    An empty list means agreement. This never fixes anything and never
    warns - a disagreement is a build failure, because a warning in CI is
    a fact nobody reads.
    """
    problems: list[str] = []

    m = _VERSION_RE.search(pyproject)
    if not m:
        raise ManifestError("could not parse version from pyproject.toml")
    if m.group(1) != manifest["version"]:
        problems.append(
            f"pyproject version {m.group(1)!r} != manifest version {manifest['version']!r}"
        )

    if BEGIN_MARK not in readme or END_MARK not in readme:
        problems.append(
            "README has no generated manifest block - the current counts have "
            "nowhere honest to live"
        )
    else:
        block = readme.split(BEGIN_MARK, 1)[1].split(END_MARK, 1)[0]
        expected = render_block(manifest).split(BEGIN_MARK, 1)[1].split(END_MARK, 1)[0]
        if block.strip() != expected.strip():
            problems.append(
                "README generated block is stale - regenerate with "
                "`python -m sovereign_stack.manifest --write`"
            )

    # Outside the block: a count is only allowed if it is dated.
    outside = _strip_generated_block(readme)
    undated: list[str] = []
    for line in outside.splitlines():
        if _BADGE_RE.search(line) and not _AS_OF_RE.search(line):
            for value in _BADGE_RE.findall(line):
                undated.append(f"badge:{value}")
        if not _COUNT_RE.search(line):
            continue
        if _AS_OF_RE.search(line):
            continue
        for value, plus, noun in _COUNT_RE.findall(line):
            undated.append(f"{value}{plus} {noun}")
    if undated:
        problems.append(
            "undated count claims outside the generated block (add `as of ...` "
            f"or move them into the block): {', '.join(sorted(set(undated)))}"
        )

    # Vacuity guard: a document that asserts nothing passes every check by
    # having nothing to check. That is not honesty, it is silence.
    if BEGIN_MARK not in readme:
        raise ManifestError(
            "README asserts no current counts anywhere - the drift check would "
            "be vacuous and would pass by saying nothing"
        )

    return problems


def _main(argv: list[str] | None = None) -> int:
    import argparse

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--write", action="store_true", help="write stack_manifest.json and update the README block"
    )
    parser.add_argument(
        "--check", action="store_true", help="fail if prose and projection disagree"
    )
    parser.add_argument("--tests-collected", type=int, default=None)
    args = parser.parse_args(argv)

    root = Path(__file__).resolve().parents[2]
    manifest = build_manifest(repo_root=root, tests_collected=args.tests_collected)
    readme_path = root / "README.md"
    readme = readme_path.read_text(encoding="utf-8")
    pyproject = (root / "pyproject.toml").read_text(encoding="utf-8")

    if args.write:
        (root / "stack_manifest.json").write_text(
            json.dumps(manifest, indent=2) + "\n", encoding="utf-8"
        )
        if BEGIN_MARK in readme and END_MARK in readme:
            head, rest = readme.split(BEGIN_MARK, 1)
            _, tail = rest.split(END_MARK, 1)
            readme_path.write_text(head + render_block(manifest) + tail, encoding="utf-8")
        print(
            f"wrote stack_manifest.json ({manifest['tools_count']} tools, v{manifest['version']})"
        )
        return 0

    if args.check:
        problems = check_docs_against_manifest(manifest, readme, pyproject)
        committed = root / "stack_manifest.json"
        if not committed.exists():
            problems.append(
                "stack_manifest.json is missing - a missing manifest is a failure, never a skip"
            )
        else:
            on_disk = json.loads(committed.read_text(encoding="utf-8"))
            drifting = {
                k for k in ("version", "tools_count", "tools") if on_disk.get(k) != manifest.get(k)
            }
            if drifting:
                problems.append(f"stack_manifest.json is stale in: {', '.join(sorted(drifting))}")
        if problems:
            print("MANIFEST CHECK FAILED - the documentation is not current:")
            for p in problems:
                print(f"  - {p}")
            return 1
        print(f"manifest check OK ({manifest['tools_count']} tools, v{manifest['version']})")
        return 0

    print(json.dumps(manifest, indent=2))
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(_main())
